### ISSUE TITLE
Anfrage. RevSoundVol

### ISSUE THREAD

**Issue by SbSh-DNA-ModDing** [JanCraymer/FS22_DisableReverseBeep#1]
Hallo, ich hatte im 19er und anfang 22er schon mal ein Script geschrieben, wo man manche Sounds in der Lautstärke ändern konnte.
Es wurde "!= einfach" die soundTemplate überschrieben.....

meine Frage: wäre es machbar in deinem Script, anstatt den RevSound auf nil zu setzten - nur die volume zu reduzieren.
indoor .1 outdoor .3 oder sowas.
Mein Problem damals war, weildie sounds ständig im update sind, wurden meine variablen füher oder später immer wieder durch die engine ausgeklinkt - sprich wieder von original überschrieben.

Vielleicht bist du da besser in der Materie ;)

Viele Grüße

¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
Hello, in the 19's and early 22's I had already written a script where you could change the volume of some sounds.
 The sound template was "!= simply" overwritten.....

 my question: would it be feasible in your script instead of setting the RevSound to nil - just reduce the volume.
 indoor .1 outdoor .3 or something.
 My problem back then was, because the sounds are constantly being updated, my variables were always released by the engine sooner or later - i.e. overwritten by the original again.

 Maybe you're better at it ;)

 Many greetings

**Comment by JanCraymer** [comment]
Hallo,

bin im Moment recht unmotiviert, was LS angeht und habe es daher nicht getestet, aber vielleicht kann man statt 
`spec.samples.reverseDrive = nil`
auch folgendes schreiben:
`spec.samples.reverseDrive.volumeScale = 0.5 `
Wenn es funktioniert, sollte das dann die Lautstärke auf 50% setzen.

Ich habe jetzt nicht gesehen, dass man da irgendwo zwischen indoor und outdoor unterscheiden kann. Ich schätze das wird irgendwo ein globaler Wert sein, inwieweit die Sounds indoor gedämpft werden.

**Comment by SbSh-DNA-ModDing** [comment]
ja der Unterschied (indoor/outdoor) wird on top noch mal multipliziert - sprich x 0.4 id | 1.0 od vom main volume des sounds
 so wie es in der template xml steht.
Ich zieh mir das einfach mal rüber und teste deine Idee, wenn ich darf.

Danke, lg

**Comment by SbSh-DNA-ModDing** [comment]
zu früh gefreut... bin an dem selben Punkt wie in meinem script damals :D
spec.samples.reverseDrive.volumeScale ist leer (nil) und wenn man was rein schreibt, wird es von der engine wieder übeschrieben...
temporärer Wert und spec.samples.reverseDrive.volumeScale geht zurück auf "nil"
schade

**Comment by JanCraymer** [comment]
Hätte ja klappen können. Vielleicht kann man die Engine dazu überreden, in dem man ihr vorgaukelt, dass der volumeScale aus der XML kommt? Bei einigen Sounds ist da ja was eingetragen.

**Comment by SbSh-DNA-ModDing** [comment]
weiß ich nicht genau.. probiere im Moment, ob ich da über den SoundManager mit SetSampleVolume dran komme.
Ich muss nur irgendwie die Samples auslesen können. Hab mir das Script von Hasse (REAdistantMotorSound) mal angesehen, da wird das auch so gemacht... ABER!  =)   ich weiß nicht welche samples welche sind.
try&error Spiel^^
